# Generated by Django 4.2.25 on 2025-10-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_friends_id_alter_messages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chat.userprofile'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['sender_name', 'receiver_name', 'timestamp'], name='chat_messag_sender__ba2620_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['-timestamp'], name='chat_messag_timesta_ab7eaa_idx'),
        ),
    ]
