# Generated by Django 4.2.25 on 2025-10-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'timestamp'], name='chat_groupm_group_i_2ff167_idx'),
        ),
    ]
