# Generated by Django 4.2.25 on 2025-10-28 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_messages_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='created_at',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
