# Generated by Django 4.2.25 on 2025-10-28 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_groupchat_admin_remove_groupchat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', to='chat.userprofile'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='chat.userprofile'),
        ),
    ]
