# Generated by Django 4.2.25 on 2025-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groupchat_created_at_alter_groupchat_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='description',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='_content',
            field=models.BinaryField(db_column='content', default=b''),
        ),
        migrations.AddField(
            model_name='messages',
            name='_description',
            field=models.BinaryField(db_column='description', default=b''),
        ),
    ]
