# Generated by Django 4.2.25 on 2025-10-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_groupmessage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='_content',
            field=models.BinaryField(blank=True, db_column='content', null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='_description',
            field=models.BinaryField(blank=True, db_column='description', null=True),
        ),
    ]
