# Generated by Django 4.2.25 on 2025-10-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_loginotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
